# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "editorial_title",
                    models.CharField(
                        default="Contributing Editor",
                        help_text="e.g. Senior Geopolitical Analyst, Energy Reporter",
                        max_length=120,
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="authors/"),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, help_text="Direct URL fallback for avatar image"
                    ),
                ),
                ("twitter_handle", models.CharField(blank=True, max_length=64)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Kinshasa, DRC or Accra, Ghana",
                        max_length=100,
                    ),
                ),
                ("is_verified", models.BooleanField(default=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
