# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Headline or Title of Document/Report", max_length=255
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        help_text="e.g. Ministry of Mines DRC, Reuters, African Union, USGS",
                        max_length=150,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "archived_url",
                    models.URLField(
                        blank=True,
                        help_text="Wayback Machine or archive link",
                        max_length=500,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=150)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("accessed_date", models.DateField(blank=True, null=True)),
                (
                    "reliability_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal assessment of the publisher and methodology",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Private newsroom fact-checking notes"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. GOV_OFFICIAL, WIRE_REUTERS_AP, ACADEMIC",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_credibility_tier",
                    models.IntegerField(
                        default=1,
                        help_text="1=Primary/Direct, 2=Secondary Wire, 3=Unofficial",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Correction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Summary of what was corrected", max_length=255
                    ),
                ),
                ("original_claim", models.TextField()),
                ("corrected_claim", models.TextField()),
                (
                    "reason_for_correction",
                    models.TextField(
                        help_text="Detailed explanation of error, origin, and corrective action"
                    ),
                ),
                ("corrected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_public_banner_active",
                    models.BooleanField(
                        default=True,
                        help_text="Displays a red correction banner at the top of the article",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="articles.article",
                    ),
                ),
                (
                    "corrected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-corrected_at"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claim_text", models.TextField(help_text="Key assertion scrutinized")),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED_FACT", "Verified Fact"),
                            ("OFFICIAL_CLAIM", "Official Claim / State Statement"),
                            ("ALLEGATION", "Allegation / Third-Party Report"),
                            ("DISPUTED", "Disputed Claim"),
                            ("UNVERIFIED", "Unverified / Developing"),
                            ("ANALYSIS", "Editorial Analysis / Synthesis"),
                            ("OPINION", "Perspective / Commentary"),
                        ],
                        db_index=True,
                        default="VERIFIED_FACT",
                        max_length=32,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Editorial explanation of how this was audited",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="articles.article",
                    ),
                ),
                (
                    "primary_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_claims",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="source",
            name="source_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="sources.sourcetype",
            ),
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("citation_number", models.PositiveIntegerField(default=1)),
                (
                    "quote_excerpt",
                    models.TextField(
                        blank=True, help_text="Exact excerpt cited from the source"
                    ),
                ),
                (
                    "public_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Paragraph 14, IMF Country Report No. 24/89'",
                        max_length=100,
                    ),
                ),
                ("page_or_timestamp", models.CharField(blank=True, max_length=64)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="articles.article",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ["citation_number"],
                "unique_together": {("article", "citation_number")},
            },
        ),
    ]
