# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("media_library", "0001_initial"),
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="Concise headline for mobile tickers and breaking bar",
                        max_length=120,
                    ),
                ),
                ("slug", models.SlugField(max_length=280, unique=True)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Dek / Sub-headline providing immediate context",
                        max_length=350,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Executive summary for syndication, SEO, and card previews",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("NEWS", "News (Fast Verified)"),
                            ("ANALYSIS", "Analysis (Interpretation & Implication)"),
                            ("EXPLAINER", "Explainer (Deep Educational Breakdown)"),
                            ("HISTORY", "History & Pre-Colonial Archive"),
                            ("DATA", "Data & Resource Journalism"),
                            ("VIDEO", "Video & Short Documentary"),
                            ("DEBATE", "Debate & Structured Perspective"),
                            ("INVESTIGATION", "Investigative Report"),
                        ],
                        db_index=True,
                        default="NEWS",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("IN_REVIEW", "Under Editor Review"),
                            ("FACT_CHECK", "Fact Check & Source Audit"),
                            ("APPROVED", "Approved for Publication"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("CORRECTED", "Published with Correction"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Full article text in Markdown / HTML formatting"
                    ),
                ),
                (
                    "structured_blocks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Interactive structured blocks: pull quotes, key facts boxes, timelines, data charts",
                    ),
                ),
                (
                    "hero_image_url",
                    models.URLField(
                        blank=True, help_text="Direct hero image URL fallback"
                    ),
                ),
                ("hero_caption", models.TextField(blank=True)),
                ("hero_credit", models.CharField(blank=True, max_length=200)),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube, Vimeo, or MP4 URL if lead story is video",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("reading_time_minutes", models.PositiveIntegerField(default=3)),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Featured on homepage top module",
                    ),
                ),
                (
                    "is_breaking",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Featured in breaking news ticker",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, help_text="Requires Senior Editor / Legal review"
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("bookmarks_count", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=160)),
                ("seo_description", models.CharField(blank=True, max_length=255)),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "internal_editorial_notes",
                    models.TextField(
                        blank=True,
                        help_text="Newsroom internal collaboration and desk notes",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="articles", to="authors.authorprofile"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="taxonomy.category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="taxonomy.country",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_as_hero",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "primary_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="taxonomy.region",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="taxonomy.subcategory",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="taxonomy.topic"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=350)),
                ("body", models.TextField()),
                ("diff_summary", models.TextField(blank=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="articles.article",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_number"],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "-published_at"], name="articles_ar_status_de59cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["content_type", "-published_at"],
                name="articles_ar_content_46fe6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "-published_at"],
                name="articles_ar_categor_82196d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articlerevision",
            unique_together={("article", "revision_number")},
        ),
    ]
