# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoStory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("SHORT_REEL", "60 Seconds of Context (Reel)"),
                            ("EXPLAINER", "Video Explainer (5-10 min)"),
                            ("DOCUMENTARY", "Documentary Feature (Longform)"),
                            ("INTERVIEW", "Diplomatic & Economic Interview"),
                        ],
                        db_index=True,
                        default="EXPLAINER",
                        max_length=32,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(help_text="Direct MP4, YouTube, or HLS stream URL"),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=180, help_text="Duration in seconds"
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="Full transcribed speech for accessibility and SEO",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "related_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_stories",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
