# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="media_library/%Y/%m/"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="Direct CDN/External URL fallback"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("DOCUMENT", "Document / PDF"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_PHOTO", "Official Photograph"),
                            ("LICENSED_WIRE", "Licensed Wire / Agency"),
                            ("STAFF_PHOTO", "Staff / Commissioned Photo"),
                            ("ARCHIVAL", "Archival / Historical Record"),
                            ("INFOGRAPHIC", "Editorial Graphic / Map / Chart"),
                            (
                                "AI_ILLUSTRATION",
                                "AI-Generated Conceptual Illustration (Non-Documentary)",
                            ),
                        ],
                        default="STAFF_PHOTO",
                        max_length=30,
                    ),
                ),
                ("alt_text", models.CharField(max_length=255)),
                ("caption", models.TextField(blank=True)),
                (
                    "credit",
                    models.CharField(
                        help_text="e.g. AFP / Getty Images or KKEVO Field Unit",
                        max_length=200,
                    ),
                ),
                ("source_organization", models.CharField(blank=True, max_length=150)),
                ("copyright_notice", models.CharField(blank=True, max_length=200)),
                ("date_captured", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=150)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
