# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_nav_visible", models.BooleanField(default=True)),
                (
                    "color_accent",
                    models.CharField(
                        default="#0066FF", help_text="Hex accent color", max_length=32
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "icon_name",
                    models.CharField(blank=True, default="Layers", max_length=64),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "iso_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 or alpha-3 code",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("capital", models.CharField(blank=True, max_length=100)),
                ("flag_emoji", models.CharField(blank=True, max_length=8)),
                (
                    "gdp_nominal_usd",
                    models.CharField(
                        blank=True, help_text="e.g. $67.5 Billion", max_length=64
                    ),
                ),
                (
                    "population",
                    models.CharField(
                        blank=True, help_text="e.g. 102.5 Million", max_length=64
                    ),
                ),
                (
                    "strategic_resources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of strategic resources (Cobalt, Lithium, Gold, etc.)",
                    ),
                ),
                (
                    "sovereignty_notes",
                    models.TextField(
                        blank=True,
                        help_text="Key national sovereignty and strategic priorities",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="countries",
                        to="taxonomy.region",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="taxonomy.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subcategories",
                "ordering": ["name"],
                "unique_together": {("category", "slug")},
            },
        ),
    ]
