# Generated by Django 5.1.15 on 2026-09-08 10:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Tracks subscriptions: daily_briefing, weekly_analysis, critical_minerals, geopolitics",
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
